services:
  flask-app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=mysql+pymysql://${user}:${password}@db/${database}
      - host=db
      - database=${database}
      - user=${user}
      - password=${password}
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${password}
      - MYSQL_DATABASE=${database}
      - MYSQL_USER=${user}
      - MYSQL_PASSWORD=${password}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped

volumes:
  mysql_data:
