"""MUN Registration Model

Revision ID: 1e448f8c63ae
Revises: 3558a0a90238
Create Date: 2025-05-19 20:18:26.387426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e448f8c63ae'
down_revision = '3558a0a90238'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mun_registration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(length=80), nullable=False),
    sa.Column('lastName', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('curr_address', sa.String(length=255), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('primaryPhone', sa.Integer(), nullable=False),
    sa.Column('secondaryPhone', sa.Integer(), nullable=False),
    sa.Column('whatsappNumber', sa.Integer(), nullable=False),
    sa.Column('foodPreferences', sa.String(length=255), nullable=False),
    sa.Column('prevEnrolled', sa.String(length=255), nullable=False),
    sa.Column('stream', sa.String(length=255), nullable=False),
    sa.Column('alreadyInMun', sa.String(length=100), nullable=False),
    sa.Column('committee', sa.String(length=100), nullable=False),
    sa.Column('secCommittee', sa.String(length=100), nullable=False),
    sa.Column('globalIssues', sa.Text(), nullable=False),
    sa.Column('futureGoal', sa.Text(), nullable=False),
    sa.Column('medicalCondition', sa.Text(), nullable=False),
    sa.Column('paymentSlip', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('firstName'),
    sa.UniqueConstraint('lastName')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('role', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')
        batch_op.drop_column('password')

    op.drop_table('mun_registration')
    # ### end Alembic commands ###
