"""Referral Code

Revision ID: 4a4b1ef5031a
Revises: 8d2db240be48
Create Date: 2025-05-22 21:08:16.806588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a4b1ef5031a'
down_revision = '8d2db240be48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mun_registration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refered_by', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('number_of_referral', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('referral_code', sa.String(length=200), nullable=False))
        batch_op.create_unique_constraint(None, ['referral_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mun_registration', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('referral_code')
        batch_op.drop_column('number_of_referral')
        batch_op.drop_column('refered_by')

    # ### end Alembic commands ###
