"""MUN Registration Model changed

Revision ID: 8d2db240be48
Revises: 1e448f8c63ae
Create Date: 2025-05-19 20:46:01.607711

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8d2db240be48'
down_revision = '1e448f8c63ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mun_registration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('address', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('primary_phone', sa.String(length=15), nullable=False))
        batch_op.add_column(sa.Column('secondary_phone', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('whatsapp_number', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('food_preference', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('previous_college', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('mun_experience', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('primary_committee', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('secondary_committee', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('global_issue_response', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('future_goals', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('medical_conditions', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('payment_proof', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('registration_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('payment_verified', sa.Boolean(), nullable=True))
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('stream',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.drop_index('firstName')
        batch_op.drop_index('lastName')
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_column('medicalCondition')
        batch_op.drop_column('firstName')
        batch_op.drop_column('committee')
        batch_op.drop_column('paymentSlip')
        batch_op.drop_column('secondaryPhone')
        batch_op.drop_column('whatsappNumber')
        batch_op.drop_column('primaryPhone')
        batch_op.drop_column('prevEnrolled')
        batch_op.drop_column('foodPreferences')
        batch_op.drop_column('globalIssues')
        batch_op.drop_column('curr_address')
        batch_op.drop_column('futureGoal')
        batch_op.drop_column('secCommittee')
        batch_op.drop_column('alreadyInMun')
        batch_op.drop_column('lastName')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mun_registration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lastName', mysql.VARCHAR(length=120), nullable=False))
        batch_op.add_column(sa.Column('alreadyInMun', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('secCommittee', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('futureGoal', mysql.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('curr_address', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('globalIssues', mysql.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('foodPreferences', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('prevEnrolled', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('primaryPhone', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('whatsappNumber', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('secondaryPhone', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('paymentSlip', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('committee', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('firstName', mysql.VARCHAR(length=80), nullable=False))
        batch_op.add_column(sa.Column('medicalCondition', mysql.TEXT(), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('lastName', ['lastName'], unique=True)
        batch_op.create_index('firstName', ['firstName'], unique=True)
        batch_op.alter_column('stream',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('payment_verified')
        batch_op.drop_column('registration_date')
        batch_op.drop_column('payment_proof')
        batch_op.drop_column('medical_conditions')
        batch_op.drop_column('future_goals')
        batch_op.drop_column('global_issue_response')
        batch_op.drop_column('secondary_committee')
        batch_op.drop_column('primary_committee')
        batch_op.drop_column('mun_experience')
        batch_op.drop_column('previous_college')
        batch_op.drop_column('food_preference')
        batch_op.drop_column('whatsapp_number')
        batch_op.drop_column('secondary_phone')
        batch_op.drop_column('primary_phone')
        batch_op.drop_column('address')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
